# version: "3"
# services:
#   mysql:
#     image: mysql:5.7
#     environment:
#     expose:
#       - 3307
#     volumes:
#       - /var/lib/mysql
#       - ./mysql/migrations:/docker-entrypoint-initdb.d
#     restart: unless-stopped
#   web:
#     build:
#       context: .
#       dockerfile: web/Dockerfile
#     volumes:
#       - ./:/web
#     ports:
#       - "3000:3000"
#     environment:
#       NODE_ENV: development
#       PORT: 3000
#     links:
#       - mysql:mysql
#     depends_on:
#       - mysql
#     expose:
#       - 3000
#     # command: ["./wait-for-it.sh", "mysql:3307"]
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_DATABASE: mydb
      MYSQL_USER: mysql
      MYSQL_PASSWORD: 1234
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3307:3306"

  adminer:
    image: adminer
    restart: always
    ports:
      - 3000:3000